### ISSUE TITLE
Question about Sitemap

### ISSUE THREAD

**Issue by marii89** [c4software/python-sitemap#15]
Hello,

This sitemap have index xml sitemap where is located all little sitemap.xml ... ?
Can i add limit e.g. I have a lot links on my website, I can add limit e.g. 10 000 links after this script stop ?
This script not add copy/same links in sitemap ?

Thanks.

**Comment by c4software** [comment]
Hi,

Sorry for the delay, 
I don't really understand your first question, can you explain? 
In the current version you can't define a limit the script crawl the entire website and then stop. 
And nope you will not have duplicate link.

**Comment by marii89** [comment]
@c4software 

this script will make more sitemap files or just one, i know depend how much is links there but this will make one sitemap file or more ?

**Comment by c4software** [comment]
One site map for all links on the website.

**Comment by c4software** [comment]
In what kind of situation you would like to create multiple files?
