### ISSUE TITLE
HTTPS urls

### ISSUE THREAD

**Issue by wernerbarnard** [c4software/python-sitemap#23]
Hi,

I noticed that even though the links in the page doesn't specify this, the <loc> tag always defaults to http://, even when the `<a href="/"></a>` doesn't include the domain?

i.e. with this command:

`python3 main.py --domain https://www.****/ --images --output sitemap.xml --verbose`

I get:

![image](https://cloud.githubusercontent.com/assets/6905546/26103256/ea67219a-3a38-11e7-9675-31e4d0c95fdb.png)

**Comment by c4software** [comment]
Nice catch

**Comment by wernerbarnard** [comment]
Works for me - thanks!
