### ISSUE TITLE
Slash missing in URL

### ISSUE THREAD

**Issue by 2globalnomads** [c4software/python-sitemap#25]
Running:
`python3 main.py --domain https://www.2globalnomads.info --output sitemap.xml --images --report --parserobots`

Output:
`<image:loc>https://www.2globalnomads.infopaivi-santeri-kannisto/subscribe.png</image:loc></image:image><image:image><image:loc>https://www.2globalnomads.infopaivi-santeri-kannisto/logo.png</image:loc>`

There should be "/" in the URL before path, between "info" and "paivi" like this "info/paivi"

The same issue happens with all local URLs. Remote URLs are all OK.

**Comment by c4software** [comment]
Nice catch! I will fix it tonight

**Comment by c4software** [comment]
Fixed. I also notice some glitch while parsing your website (the //analytics… and the mailto link) its also fixed.

**Comment by 2globalnomads** [comment]
Works, great! One more issue left with data URI images that should be excluded and an improvement proposal. I will open a new ticket for those.
