### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by 2globalnomads** [c4software/python-sitemap#32]
Script adds the root directory twice to the sitemap, the first entry in the beginning is without ending slash and the second entry at the end is with the ending slash.
See: 
`python3 sitemap.py --domain https://www.2globalnomads.info --image --output sitemap.xml`
Output:
`<url><loc>https://www.2globalnomads.info</loc><lastmod>2017-08-22T15:28:56+00:00</lastmod>`
...
`<url><loc>https://www.2globalnomads.info/</loc><lastmod>2017-08-22T15:28:56+00:00</lastmod>`

**Comment by c4software** [comment]
Should be fixed in the last version.

**Comment by 2globalnomads** [comment]
Yeah, now it works. Thanks!

**Comment by 2globalnomads** [comment]
I am coding a web interface for your script. Let me know if you want to check it out before I release it.
