### ISSUE TITLE
UnicodeDecodeError possibly with Scandinavian letters

### ISSUE THREAD

**Issue by 2globalnomads** [c4software/python-sitemap#33]
Command
`python3 ~/sitemap/python-sitemap-master/main.py --domain https://www.books.2globalnomads.info --image --output sitemap.xml`
Output
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte`

With multiple errors: HTTP Error 404: Not Found

**Comment by 2globalnomads** [comment]
Same issue with scandinavian letters here:
`python3 ~/sitemap/python-sitemap-master/main.py --domain https://www.xetnet.fi --image --output sitemap.xml --verbose `

**Comment by c4software** [comment]
For the first website, its because of ebook, the crawler open the « target » uri, but the content is not  really navigable so its fail. 

A fix will be included in the next commit.

For the « xetnet.fi », i start the crawler right now i will check this case when the error will appear.

**Comment by 2globalnomads** [comment]
OK. Those are likely due to Scandinavian special letters such as ö and ä. The character encoding in URLs is crucial to be unicode for handling them.

**Comment by c4software** [comment]
I don’t have the issue anymore with the « xetnef.fi » website.

I also test with french letters « é, à, ô, … » its seems ok.
