### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by 2globalnomads** [c4software/python-sitemap#34]
Command
`python3 ~/sitemap/python-sitemap-master/main.py --domain https://www.forum.2globalnomads.info --image --output sitemap.xml --verbose`

**Comment by c4software** [comment]
Its due to sid, you have to « drop » : 

```
python3 main.py --domain https://www.forum.2globalnomads.info --image --verbose --drop "sid=[a-z0-9]{32}"
```
