### ISSUE TITLE
Double entry if 2 slashes in the url

### ISSUE THREAD

**Issue by 2globalnomads** [c4software/python-sitemap#38]
Command:
`python3 ~/sitemap/python-sitemap-master/main.py --domain https://www.2globalnomads.info//web-design-websites/ --image --output sitemap.xml --report`
This location will appears twice in the sitemap because of the double slash:

> \<loc>https://www.2globalnomads.info//web-design-websites/<\/loc>

**Comment by c4software** [comment]
The best way to resolve this issue is (i think) to check the domain before running the command.

**Comment by 2globalnomads** [comment]
I believe it should ignore all double slashes and treat them as one slash to function properly except in the protocol.

**Comment by 2globalnomads** [comment]
I checked it. The correct solution is search from the path all double slashes and replace them with single slashes, and do this as many times as there are no more double slashes left. A slash is an empty, non-existent directory which is like null,
