### ISSUE TITLE
Online interface for the script

### ISSUE THREAD

**Issue by 2globalnomads** [c4software/python-sitemap#39]
This is not really an issue, but I did not find any better/other way to talk with you.

I made an online interface for the script. I am updating your code there manually after testing each release by myself first. Hopefully it will make it easier for people to run the script and help to attract others join the projects and do testing or possibly even coding.

The interface is available at: [https://www.2globalnomads.info/web-design-websites/#generateimagesitemap](https://www.2globalnomads.info/web-design-websites/#generateimagesitemap).

**Comment by c4software** [comment]
Thanks, did you made the source available somewhere ?

**Comment by 2globalnomads** [comment]
I can if you want, however it's just a few lines of PHP code executing system commands and then printing the output to a html page like this:
```
exec("python3 main.py --domain " . $url . " --image --parserobots --output " . $tempfile);
exec("xmllint --format $tempfile -o " . $tempfile);
readfile($tempfile);
```

The rest is just static world-readable html. I am not sure is there any added value for anyone, but if someone wants I am happy to give it. I saw you are using GPL3. I myself prefer releasing in the Public Domain. It's not that I don't like Richard, but I just don't agree with about about limiting the freedom of software in any way.

**Comment by c4software** [comment]
Be carefull with the sample code you share. If you make this tool public someone with bad intention can inject nasty parameters instead of the url.
