### ISSUE TITLE
Adding trailing '/' to all URLs

### ISSUE THREAD

**Issue by dgursh** [c4software/python-sitemap#43]
All of my site's URLs include a trailing '/'
```
https://www.example.com/
https://www.example.com/dir/
```

not the following:

```
https://www.example.com
https://www.example.com/dir
```

This script made all of my links use the links without the trailing '/'

How do I add the trailing '/' in?

**Comment by 2globalnomads** [comment]
Please post the exact command you are using and part of the exact output you get with the error.
