### ISSUE TITLE
Working with Angular sites?

### ISSUE THREAD

**Issue by tspicer** [c4software/python-sitemap#44]
Wanted to try and see if this would work with single page apps like Angular and it appears it will only pick up the index page. Hopefully support can be added to support these types of use cases. Thanks.

**Comment by c4software** [comment]
Hi,

Sorry for the delay! Its a nice idea… But since its a crawler, implementing this in the project seems a bit complicated… But its a nice idea, i will look at it !

Thanks for the suggestion.
