### ISSUE TITLE
Error: No space left on device

### ISSUE THREAD

**Issue by FranciscoPaixao** [c4software/python-sitemap#46]
My VPS has a lot of space, but the script always gives this error
NOTE: I use the Screen program to run the script in the background
![screenshot_20180210-184154](https://user-images.githubusercontent.com/26686029/36066938-184b6c6e-0e92-11e8-8463-e2e600d0404a.png)

**Comment by c4software** [comment]
Interesting, your website seems very huge, did you open the sitemap.xml to check if its contains only links ?

**Comment by FranciscoPaixao** [comment]
Yes, but the sitemap is invalid

**Comment by c4software** [comment]
Its logic because the process was interrupted. Can you share the file with me (I would like to check the contents) ?
