### ISSUE TITLE
Please move the project away from GitHub

### ISSUE THREAD

**Issue by santerikannisto** [c4software/python-sitemap#47]
I just read that Microsoft is acquiring GitHub. I have seen enough of Microsoft love for open source for a life time to avoid everything that involves them. It is at best just a kiss of death and soon all users are required to install Microsoft malware and open Microsoft accounts to use GitHub, all all our information is for sale. I am quitting GitHub. So long and thanks for all the fish.

**Comment by c4software** [comment]
The project is already on gitlab : https://gitlab.com/vbrosseau/python-sitemap

**Comment by santerikannisto** [comment]
Excellent, thanks!
