### ISSUE TITLE
sintax error

### ISSUE THREAD

**Issue by francisco-baptista** [c4software/python-sitemap#53]
Just pulled the code and I get this:

 $ python main.py www.cafonline.com --output sitemap.xml --verbose  
 Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import crawler
  File "/home/francisco/python-sitemap/crawler.py", line 105
    print(config.xml_header, file=self.output_file)
                                 ^
 SyntaxError: invalid syntax

**Comment by c4software** [comment]
What is your python version ?
