### ISSUE TITLE
urls not saved to sitemap.xml

### ISSUE THREAD

**Issue by crossmania337** [c4software/python-sitemap#80]
This is the first script I am ever running.

Thank you for creating it.

After it finished, there are 634 crawled urls. 

However, the sitemap.xml file in the directory is empty. How do I fix this?

Thank you in advance.

***

This is what I see:

![Untitled](https://user-images.githubusercontent.com/106387277/170703625-14b03fce-9acd-461a-ace7-5b79053940f1.jpg)

**Comment by c4software** [comment]
Hi,

Can you tel me what command arguments did you use ?

Best

**Comment by crossmania337** [comment]
Ran it once again and it was fine. Thank you.
