### ISSUE TITLE
Windows and/or Python 3.7.2?

### ISSUE THREAD

**Issue by VVilku** [c4software/python-sitemap#82]
Hello
I have a problem with python-sitemap on Windows and Python 3.7.2. 
I haven't looked into the problem yet, but whatever I do (even 'empty'/solo 'python main.py') I get:

```
Traceback (most recent call last):
  File "C:\! git !\python-sitemap\main.py", line 8, in <module>
    import crawler
  File "C:\! git !\python-sitemap\crawler.py", line 240
    image_link = f"{self.domain.strip("/")}{image_link.replace("./", "/")}"
                                                                 ^
SyntaxError: invalid syntax
```

**Comment by c4software** [comment]
Hi,

There was a bug in the last commit. It is now fixed.

**Comment by VVilku** [comment]
Thank you :) 
I was going to take a look at it, but I had a family trip :)
