### ISSUE TITLE
Option to specify bot for robots.txt

### ISSUE THREAD

**Issue by Garrett-R** [c4software/python-sitemap#87]
For a site that has a `robots.txt` like:

```robots.txt
User-agent: *
Disallow: /

User-agent: Googlebot
Allow: /
Disallow: /login
```

it would be nice if there was an option to run the script as Googlebot, so it follow those rules.

**Comment by c4software** [comment]
It's a really nice idea !

I will look at this soon.

**Comment by Garrett-R** [comment]
Cool!  My team can also submit a PR if that helps!
